import React from 'react';
import '../App.css';
import StatusBar from '../Subcomponents/Footer';
import Footer from '../Subcomponents/StatusBar';
import NoteBox from '../Subcomponents/NoteBox';
import SongBox from '../Subcomponents/SongBox';
import Player from "../Subcomponents/Player";


class MixTape extends React.Component {
  constructor(props) {
    super(props);
    this.state = { }
  }


  render () {
    console.log(this.props.location.state.testValue)
    return (
      <div>
        <div id='viewscreen'>
          <StatusBar />
          <Footer />
          <NoteBox />
          <div style={styles.infoBox}>
            <div style={styles.tapeName}>
              Mixtape #1
            </div>
            <div style={styles.follow}>
              FOLLOW
            </div>
            <div style={styles.text}>
              Generated by <b>Ruby F00</b>
            </div>
            <div style={styles.text}>
              <b>Tags</b> : {this.props.location.state.testValue.join(' , ')}
            </div>
          </div>
          <Player />
        </div> 
      </div>
    );
  }
}

const styles = {
  infoBox : {
    position: "absolute",
    top: "44%",
    left: "25%",
    textAlign: "center",
    height: 100,
    width: 200
  },
  follow : {
    marginLeft: 40,
    textAlign: "center",
    marginTop: 15,
    color: "rgb(130,130,130)",
    borderStyle: "solid",
    borderRadius: '25px',
    width: "55%"
  },
  text : {
    marginTop: 10,
    fontSize: 12
  },
  tapeName: {
    fontSize: 28,
  }
}

export default MixTape;
